# Generated by Django 3.1.7 on 2021-03-27 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorei', '0008_auto_20210326_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('first_name', models.TextField(db_column='first_name', max_length=10)),
                ('middle_name', models.TextField(blank=True, db_column='middle_name', max_length=10, null=True)),
                ('last_name', models.TextField(blank=True, db_column='last_name', max_length=10, null=True)),
                ('email_address', models.EmailField(db_column='email_address', max_length=40)),
                ('mobile_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('password', models.CharField(db_column='password', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='money',
            name='money_id',
            field=models.AutoField(db_column='money_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='money',
            name='transaction_id',
            field=models.CharField(db_column='transaction_id', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stationery',
            name='stationery_id',
            field=models.AutoField(db_column='stationery_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(db_column='user_id', primary_key=True, serialize=False),
        ),
    ]
